version: "1.0"
stages:
  - "clone"
  - "build"
  - "test"
  - "push"
  - "package"
  - "deploy"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"
    git: "github-francisco"
    stage: "clone"

  build:
    title: "Building Docker image"
    type: "build"
    image_name: "sales-dev/demochat"
    working_directory: "${{clone}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"

  unit_test:
    title: "Running Unit Tests"
    image: "${{build}}"
    working_directory: "${{clone}}"
    commands:
      - "yarn install --silent"
      - "yarn test"
    services:
      composition:
        my_mongo_Service:
          image: "mongo:latest"
          ports:
            - 27017
    stage: "test"
    
  unit_test_reporting_step:
    title: "Generating test reporting"
    image: "codefresh/cf-docker-test-reporting"
    working_directory: "${{clone}}"
    environment:
      - "BUCKET_NAME=codefreshdemo"
      - "CF_STORAGE_INTEGRATION=sales-dev-azure-blob"
    stage: "test"

  push:
    title: "Pushing Docker image to ACR"
    type: "push"
    candidate: "${{build}}"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    image_name: "sales-dev/demochat"
    registry: "acr"
    stage: "push"

  package:
    title: "Packing/Pushing Helm Chart to ACR"
    type: "helm"
    arguments:
      helm_version: "3.0.3"
      action: "push"
      kube_context: "sales-dev-aks@BizSpark Plus"
      chart_name: "${{CF_VOLUME_PATH}}/${{CF_REPO_NAME}}/helm/demochat"
    stage: "package"

  deploy:
    title: "Deploying Helm chart to AKS"
    type: "helm"
    arguments:
      helm_version: "3.0.3"
      chart_name: "demochat"
      chart_version: "0.2.0"
      release_name: "demochat"
      kube_context: "sales-dev@codefresh-sa"
      namespace: "demochat"
      custom_values:
        - "image.tag=${{CF_BRANCH_TAG_NORMALIZED}}"
    stage: "deploy"
