# Deploys Aqua all-in-one
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: aqua-portal
  labels:
    app: aqua-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aqua-portal
  template:
    metadata:
      labels:
        app: aqua-portal
    spec:
      volumes:
        - name: docker-socket-volume
          hostPath:
            path: /var/run/docker.sock
            type: File
      containers:
        - name: aqua-portal
          image: 'registry.aquasec.com/all-in-one:4.0.rc7'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: docker-socket-volume
              mountPath: /var/run/docker.sock
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            privileged: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 40
      dnsPolicy: ClusterFirst
      securityContext: {}
      imagePullSecrets:
        - name: codefresh-generated-registry.aquasec.com-aqua-aqua
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: aqua-portal
spec:
  ports:
    - name: http1
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: aqua-portal
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster


