apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{.Release.Name}}-mongo"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: "{{.Release.Name}}-mongo"
    release: {{.Release.Name}}
    heritage: Tiller
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: "{{.Release.Name}}-mongo"
  template:
    metadata:
      labels:
        app: "{{.Release.Name}}-mongo"
    spec:
      containers:
      - name: "{{.Release.Name}}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
        - name: RELNAME
          value: {{.Release.Name}}
#        livenessProbe:
#          httpGet:
#            path: /
#            port: {{ .Values.service.internalPort }}
#        readinessProbe:
#          httpGet:
#            path: /
#            port: {{ .Values.service.internalPort }}
#        resources:
